#!/bin/bash

###############################################################################
# Log File Initialization Script
#
# Creates and initializes all log files required by the SDN DDoS detection
# system. Each file is created with proper headers and permissions.
#
# Files Created:
#   attacks_log.csv         - Attack detection records (written by controller)
#   controller_log.txt      - Controller events and messages
#   performance_metrics.csv - System performance measurements
#   attack_history.txt      - Attack generation history (written by attack_generator.sh)
#
# Usage:
#   cd logs
#   bash init_logs.sh
#
###############################################################################

# Resolve script directory (logs/ directory)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Timestamp for initialization messages
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# Track results
SUCCESS=0
TOTAL=0

###############################################################################
# Function: create_file
# Arguments: $1=filename, $2=description
# Creates a file and sets permissions to 640
###############################################################################
create_file() {
    local filepath="${SCRIPT_DIR}/$1"
    local description="$2"

    TOTAL=$((TOTAL + 1))

    if chmod 640 "$filepath" 2>/dev/null; then
        SUCCESS=$((SUCCESS + 1))
        echo "  [OK] $1 - $description"
    else
        echo "  [FAIL] $1 - Could not set permissions"
    fi
}

###############################################################################
# Main
###############################################################################
echo ""
echo "============================================================"
echo "  Log File Initialization"
echo "  Directory: ${SCRIPT_DIR}"
echo "  Timestamp: ${TIMESTAMP}"
echo "============================================================"
echo ""

# =========================================================================
# 1. attacks_log.csv
#    Written by: sdn_controller/mitigation_module.py (_log_attack method)
#    Read by:    logs/analyze_logs.py
# =========================================================================
TOTAL=$((TOTAL + 1))
ATTACKS_LOG="${SCRIPT_DIR}/attacks_log.csv"
echo "timestamp,src_ip,dst_ip,attack_type,packet_rate,action,switch" \
    > "$ATTACKS_LOG"
if chmod 640 "$ATTACKS_LOG" 2>/dev/null; then
    SUCCESS=$((SUCCESS + 1))
    echo "  [OK] attacks_log.csv - Attack detection records"
else
    echo "  [FAIL] attacks_log.csv - Could not create or set permissions"
fi

# =========================================================================
# 2. controller_log.txt
#    Written by: sdn_controller/mitigation_module.py (Ryu logger)
#    Config:     sdn_controller/ryu.conf (log_file setting)
# =========================================================================
TOTAL=$((TOTAL + 1))
CONTROLLER_LOG="${SCRIPT_DIR}/controller_log.txt"
echo "[${TIMESTAMP}] Controller log initialized" \
    > "$CONTROLLER_LOG"
echo "[${TIMESTAMP}] SDN DDoS Detection System - Log File" \
    >> "$CONTROLLER_LOG"
echo "[${TIMESTAMP}] Waiting for controller startup..." \
    >> "$CONTROLLER_LOG"
if chmod 640 "$CONTROLLER_LOG" 2>/dev/null; then
    SUCCESS=$((SUCCESS + 1))
    echo "  [OK] controller_log.txt - Controller event log"
else
    echo "  [FAIL] controller_log.txt - Could not create or set permissions"
fi

# =========================================================================
# 3. performance_metrics.csv
#    Written by: utilities/performance_monitor.py
#    Read by:    logs/analyze_logs.py
# =========================================================================
TOTAL=$((TOTAL + 1))
PERF_LOG="${SCRIPT_DIR}/performance_metrics.csv"
echo "timestamp,cpu_percent,memory_mb,active_flows,attacks_detected,avg_latency_ms" \
    > "$PERF_LOG"
if chmod 640 "$PERF_LOG" 2>/dev/null; then
    SUCCESS=$((SUCCESS + 1))
    echo "  [OK] performance_metrics.csv - Performance measurements"
else
    echo "  [FAIL] performance_metrics.csv - Could not create or set permissions"
fi

# =========================================================================
# 4. attack_history.txt
#    Written by: traffic_generation/attack_generator.sh
# =========================================================================
TOTAL=$((TOTAL + 1))
ATTACK_HIST="${SCRIPT_DIR}/attack_history.txt"
{
    echo "=== Attack History Log ==="
    echo "Initialized: ${TIMESTAMP}"
    echo "Generated by: traffic_generation/attack_generator.sh"
    echo "---"
} > "$ATTACK_HIST"
if chmod 640 "$ATTACK_HIST" 2>/dev/null; then
    SUCCESS=$((SUCCESS + 1))
    echo "  [OK] attack_history.txt - Attack generation history"
else
    echo "  [FAIL] attack_history.txt - Could not create or set permissions"
fi

# =========================================================================
# Summary
# =========================================================================
echo ""
echo "============================================================"
echo "  Initialization Complete: ${SUCCESS}/${TOTAL} files created"
echo "============================================================"
echo ""

if [ $SUCCESS -eq $TOTAL ]; then
    echo "  All log files initialized successfully."
else
    echo "  WARNING: Some files could not be initialized."
    echo "  Check directory permissions: ${SCRIPT_DIR}"
fi

echo ""
echo "  File permissions set to 640 (rw-r-----)"
echo ""
echo "  These logs will be populated when:"
echo "    - Controller starts:  attacks_log.csv, controller_log.txt"
echo "    - Monitor runs:       performance_metrics.csv"
echo "    - Attacks generated:  attack_history.txt"
echo ""
